# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Second breakfast'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Supper'), (6, 'Other')])),
                ('meal_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512, null=True)),
                ('calories', models.FloatField(null=True)),
                ('carbohydrates', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('salt', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('category', models.ManyToManyField(to='manager.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.IntegerField(choices=[(1, 'ml'), (2, 'g')])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Product')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='product',
            field=models.ManyToManyField(through='manager.Quantity', to='manager.Product'),
        ),
    ]
