# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_meal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='user',
            new_name='created_by',
        ),
    ]
