# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_auto_20170529_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(null=True)),
                ('carbohydrates', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('salt', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
