# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
